version: '3.8'

services:
  bd:
    build:
      context: .
      dockerfile: Dockerfile-bd
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "PassWord123."
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "8080:8080"
      - "443:443"
      - "4003:4003"
      - "5003:5003"
    depends_on:
      - bd
